import stickyHeader from "./components/stickyHeader";
import hamburgerMenu from "./components/hamburgerMenu";
import dropDownMenu from "./components/dropDownMenu";
import slider from "./components/slider";
import sliderPagination from "./components/sliderPagination";
import year from "./components/year";
import popUp from "./components/popUp";
import filterItems from "./components/filterItems";
import intersection from "./components/intersection";
import wordSplit from "./components/wordSplit";

stickyHeader();
hamburgerMenu();
dropDownMenu();
slider();
sliderPagination();
year();
popUp();
filterItems();
intersection();
wordSplit();
